/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zdrkesybivnirdpvmkvy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkcmtlc3liaXZuaXJkcHZta3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MTE1MjgsImV4cCI6MjA4OTE4NzUyOH0.vWvRZHSLTVxJpLzEjQYogzjRmI2NKCbVtD-wh-7qvVE"